### ISSUE TITLE
Improve internal implementation for Proposal polymorphism

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/vit-servicing-station#135]
Action points after #134:

- [x] Eliminate a bogus `challenge_type` member in the `Proposal` data model: #138
- [x] Switch from a wide sparse proposals table to challenge type-specific tables and unify the proposals data sets obtained from subqueries with joins specific to each challenge type. Alternatively, introduce a dynamic system of custom per-challenge field names to mirror IdeaScale (in harmony with the IdeaScale importer).

**Comment by danielSanchezQ** [comment]
Implemented in https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9f4d4c1e76370d50e1e0722538ee4beb
