### ISSUE TITLE
Improve the GraphQL schema

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/vit-servicing-station#139]
If we want to maintain a GraphQL API, it should be made more idiomatic.

- [ ] Instead of exposing fields on `Proposal` that are really joined from `Challenge` or `Voteplan` tables, provide those as mounted objects.
- [ ] Subtyping of proposals with challenge type-specific fields using a union type.

**Comment by danielSanchezQ** [comment]
GraphQL support was dropped
