### ISSUE TITLE
Rest - endpoint to retrieve fund/vote/rewards static information

### ISSUE THREAD

**Issue by rinor** [input-output-hk/vit-servicing-station#3]
Need to provide at least the following information:
- Fund name
- Fund goal statement
- Voting power info content: Can be anything, but probably just the main chain snapshot datetime
- Rewards info content: Can be anything, but probably just the rewards distribution datetime
- List of **voteplan_id**s - future usage

```json
{
  "fund_name": "Fund0 ...",
  "fund_goal": "Support innovative projects",
  "voting_power_info": "June 3rd 2020",
  "rewards_info": "June 21st 2020",
  "vote_plans": [
    "7c1e49c31425c03cef428c313d1d438800b0ef8101532188e3c1e0372d2eae76"
  ]
}

```
---

- [x] api definition
- [x] implementation

**Comment by danielSanchezQ** [comment]
Implemented in #15
