### ISSUE TITLE
`tls` field is required when starting service with --in-settings-file parameter

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/vit-servicing-station#32]
File `config.json` :
```
{
  "address": "127.0.0.1:3030",
  "db_url": "test/vit_station_new.db",
  "block0_path": "test/block0.bin"
}
```
Command :
` cargo run -- --db-url test\vit_station_new.db --block0-path test\block0.bin  --in-settings-file config.json`

Output:

`thread 'main' panicked at 'Error loading settings from file config.json: missing field `tls` at line 5 column 1', src\main.rs:24:13`

**Comment by dkijania** [comment]
Actually workaround is to fill it with nulls or dump settings,but i don't know if this is convenient:

```{"address":"0.0.0.0:3030","tls":{"cert_file":null,"priv_key_file":null},"cors":{"allowed_origins":null,"max_age_secs":null},"db_url":"test\\vit_station_new.db","block0_path":"test\\block0.bin"}```

**Comment by danielSanchezQ** [comment]
It actually is enough setting that `cors` and `tls` as empty:
```json
{
  "address": "127.0.0.1:3030",
  "db_url": "test/vit_station_new.db",
  "block0_path": "test/block0.bin",
  "tls": {},
  "cors": {}
}
```
