### ISSUE TITLE
Health checkpoint

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/vit-servicing-station#42]
Proposal to add a simple rest method which just return success code if server is up and ready. Something like in jormungandr rest api: `node/stats` endpoint

**Comment by danielSanchezQ** [comment]
What do you suggest would be a good response for this?

**Comment by dkijania** [comment]
Something really simple like endpoint:
```
/api/v0/health
```
and response:
```
{
 "status": "Ok"
}
```

Which means that service is up. 

This can be expanded to verify connection with database or to verify token is valid
