### ISSUE TITLE
Make rest endpoints consistent

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/vit-servicing-station#47]
i think rest endpoints for proposals and funds should be all in plural or singular form.
Right now, we have:

`/api/v0/proposals` & `/api/v0/fund`

it should be 

`/api/v0/proposals` & `/api/v0/funds`
or
`/api/v0/proposal` & `/api/v0/fund`

**Comment by danielSanchezQ** [comment]
Same as [this](https://github.com/input-output-hk/vit-servicing-station/issues/48#issuecomment-655955306)
