### ISSUE TITLE
/api/v0/fund endpoint should return collection not single item

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/vit-servicing-station#48]
I think fund endpoint should behave as proposals endpoint. If we query `fund` endpoint it return single fund while it should return collection 

`Request: http://127.0.0.1:10810/api/v0/fund`
```Response: Response { url: "http://127.0.0.1:10810/api/v0/fund", status: 200, headers: {"content-type": "application/json", `"content-length": "775", "date": "Wed, 08 Jul 2020 08:36:22 GMT"} }```
```
Body: {"id":1,"fund_name":"hey oh let's go","fund_goal":"test this endpoint","voting_power_info":">9000","rewards_info":"not much","fund_start_time":"2020-07-08T08:36:21+00:00","fund_end_time":"2020-07-08T08:36:21+00:00","next_fund_start_time":"2020-07-08T08:36:21+00:00","chain_vote_plans":[{"id":1,"chain_voteplan_id":"voteplain_id","chain_vote_start_time":"2020-07-08T08:36:21+00:00","chain_vote_end_time":"2020-07-08T08:36:21+00:00","chain_committee_end":"2020-07-08T08:36:21+00:00","chain_voteplan_payload":"none","fund_id":1},{"id":2,"chain_voteplan_id":"test_vote_plan","chain_vote_start_time":"2020-07-08T08:36:21+00:00","chain_vote_end_time":"2020-07-08T08:36:21+00:00","chain_committee_end":"2020-07-08T08:36:21+00:00","chain_voteplan_payload":"foopayload","fund_id":1}]}
```

**Comment by danielSanchezQ** [comment]
We are fitting with the API already defined in [jorvit](https://github.com/input-output-hk/jorvit) since it is the one they used for the tests. We can talk with @rinor and see what can be done about changes on this.

**Comment by rinor** [comment]
The reasoning behind that is related to the fact that right now that endpoint is supposed to report at **most** 1 (one) fund info data. There is no usage defined yet regarding multiple funds reports, nevertheless we could change that to `funds` without affecting the production on the mobile app side (we could rewrite `fund` - `funds` on the proxy entry point temporarily until the app completes the update, or provide both endpoints on the vit-service side).
