### ISSUE TITLE
fund/{id} and proposals/{id} endpoints returns all data for wrong ids

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/vit-servicing-station#49]
Below behavior regards fund and proposals endpoints

if we query non-existing id like below:
`Request: http://127.0.0.1:10614/api/v0/proposals/a`
we get 200 and server returns entire proposals collections
```Response: Response { url: "http://127.0.0.1:10614/api/v0/proposals/a", status: 200, headers: {"content-type": "application/json", "content-length": "879", "date": "Wed, 08 Jul 2020 08:38:17 GMT"} }```

The same is for overflow id (> i32 max)

`Request: http://127.0.0.1:10614/api/v0/proposals/3147483647`
we get 200 and server returns entire proposals collections
```Response: Response { url: "http://127.0.0.1:10614/api/v0/proposals/3147483647", status: 200, headers: {"content-type": "application/json", "content-length": "879", "date": "Wed, 08 Jul 2020 08:38:37 GMT"} }```

**Comment by danielSanchezQ** [comment]
This is a bug in the `warp::filter` composition in the app. Will take a look at it.
