### ISSUE TITLE
incorrect behavior of out-settings-file parameter ?

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/vit-servicing-station#62]
`--out-settings-file` parameter is supposed to dump all command line parameters into json file. I've created test in which i provide:
 `in_settings.json` file with content:

```ServiceSettings { in_settings_file: None, out_settings_file: None, address: V4(127.0.0.1:10740), tls: Tls { cert_file: None, priv_key_file: None }, cors: Cors { allowed_origins: None, max_age_secs: None }, db_url: "C:\\Users\\Dariusz\\AppData\\Local\\Temp\\.tmpRp10zA\\vit_station.db", block0_path: "../resources/tests/block0.bin" }```

and run command :
`vit-servicing-station-server --in-settings-file in_settings.json --out-settings-file out_settings.json`

However, output file contains different content than input file:

```
 left: `ServiceSettings { in_settings_file: None, out_settings_file: None, address: V4(127.0.0.1:10740), tls: Tls { cert_file: None, priv_key_file: None }, cors: Cors { allowed_origins: None, max_age_secs: None }, db_url: "C:\\Users\\Dariusz\\AppData\\Local\\Temp\\.tmpRp10zA\\vit_station.db", block0_path: "../resources/tests/block0.bin" }`,
 right: `ServiceSettings { in_settings_file: None, out_settings_file: None, address: V4(0.0.0.0:3030), tls: Tls { cert_file: None, priv_key_file: None }, cors: Cors { allowed_origins: None, max_age_secs: None }, db_url: "./db/database.sqlite3", block0_path: "./resources/v0/block0.bin" }`'
```

Difference is that `db_url` and `block0_path` are set to defaults. Is it expected behavior? since I provided a very dummy example (i don't know if anyone would just pipe from in_settings_file to out_settings_file like above),

**Comment by danielSanchezQ** [comment]
This is a bug. 
It should dump the default data override by the arguments passed to the binary.
I'll check about it.

**Comment by danielSanchezQ** [comment]
Ok, I actually did not understood properly the question.
It is **working** as expected.
The input file overrides all the arguments passed to the `cli`, since it should have the full information.
But, the dumping is happening before the loading. I'm creating a quick-fix for this.

**Comment by danielSanchezQ** [comment]
#63 should fix it and we can check it with the test in #56
