### ISSUE TITLE
Start the service even if block0 in not yet available

### ISSUE THREAD

**Issue by rinor** [input-output-hk/vit-servicing-station#84]
Right now if `block0` is not found on `--block0-path` upon service start, the service terminates.
https://github.com/input-output-hk/vit-servicing-station/blob/5e77728fa7d6f4d3e89608a2ecdab9f14e9ece7c/vit-servicing-station-server/src/main.rs#L49-L54

There is a case scenario where the service may need to be started before that `block0` is know/available.
Once the `block0` is available, we can place that in the expected `--block0-path` and the service should be able to detect and provide it through the api

**Comment by danielSanchezQ** [comment]
What should be the response in case we do not have the block0 available? Not available?

**Comment by rinor** [comment]
I would say `200 OK` as http, smth like this for now
```
< HTTP/1.1 200 OK
< content-type: application/octet-stream
< content-length: 0
```
and will check for this to be handled as `Blockchain not ready` on the other app side
