### ISSUE TITLE
No validations for block0 path

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/vit-servicing-station#90]
When running command:

```
"C:\\Work\\iohk\\vit-servicing-station\\target\\debug\\vit-servicing-station-server.exe" "--block0-path" "//tmp/block0.bin" "--db-url" "C:\\Users\\Dariusz\\AppData\\Local\\Temp\\.tmpnxxypK\\vit_station.db"
```

I expect to recieve an error saying that block0-path doesn't exist, while server is running

**Comment by rinor** [comment]
The behavior was changed due to business requirements. Please check https://github.com/input-output-hk/vit-servicing-station/issues/84 for more information.
